# 作業
- 新增一個欄位 `customized_age_grp`，把 `age` 分為 (0, 10], (10, 20], (20, 30], (30, 50], (50, 100] 這五組，
'(' 表示不包含, ']' 表示包含  
- Hints: 執行 ??pd.cut()，了解提供其中 bins 這個參數的使用方式

# [作業目標]
- 請同學試著查詢 pandas.cut 這個函數還有哪些參數, 藉由改動參數以達成目標
- 藉由查詢與改動參數的過程, 熟悉查詢函數的方法與理解參數性質, 並了解數值的離散化的調整工具

# [作業重點]
- 仿照 In[3], In[4] 的語法, 並設定 pd.cut 的參數以指定間距

In [1]:
# 載入套件
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# 初始設定 Ages 的資料
ages = pd.DataFrame({"age": [18,22,25,27,7,21,23,37,30,61,45,41,9,18,80,100]})

#### 等寬劃分

In [3]:
# 新增欄位 "equal_width_age", 對年齡做等寬劃分
ages["equal_width_age"] = pd.cut(ages["age"], 4)

In [4]:
# 觀察等寬劃分下, 每個種組距各出現幾次
ages["equal_width_age"].value_counts() # 每個 bin 的值的範圍大小都是一樣的

(6.907, 30.25]    10
(30.25, 53.5]      3
(76.75, 100.0]     2
(53.5, 76.75]      1
Name: equal_width_age, dtype: int64

#### 等頻劃分

In [5]:
# 新增欄位 "equal_freq_age", 對年齡做等頻劃分
ages["equal_freq_age"] = pd.qcut(ages["age"], 4)

In [6]:
# 觀察等頻劃分下, 每個種組距各出現幾次
ages["equal_freq_age"].value_counts() # 每個 bin 的資料筆數是一樣的

(42.0, 100.0]     4
(26.0, 42.0]      4
(20.25, 26.0]     4
(6.999, 20.25]    4
Name: equal_freq_age, dtype: int64

In [7]:
# 把 age 分為 (0, 10], (10, 20], (20, 30], (30, 50], (50, 100] 這五組
bins = [0,10,20,30,50,100]
ages["customized_age_grp"] = pd.cut(ages["age"], bins) 
ages["customized_age_grp"].value_counts()

(20, 30]     6
(50, 100]    3
(30, 50]     3
(10, 20]     2
(0, 10]      2
Name: customized_age_grp, dtype: int64

In [8]:
# 使用retbins參數，看pd.cut()如何劃分區間
pd.cut(ages["age"], bins, retbins = True) 

(0      (10, 20]
 1      (20, 30]
 2      (20, 30]
 3      (20, 30]
 4       (0, 10]
 5      (20, 30]
 6      (20, 30]
 7      (30, 50]
 8      (20, 30]
 9     (50, 100]
 10     (30, 50]
 11     (30, 50]
 12      (0, 10]
 13     (10, 20]
 14    (50, 100]
 15    (50, 100]
 Name: age, dtype: category
 Categories (5, interval[int64]): [(0, 10] < (10, 20] < (20, 30] < (30, 50] < (50, 100]],
 array([  0,  10,  20,  30,  50, 100]))

In [9]:
# 預設不包含左邊的界值，包含右邊的界值
# 設定right參數為False，即變為包含左邊的界值，不包含右邊的界值
pd.cut(ages["age"], bins, right=False) 

0      [10.0, 20.0)
1      [20.0, 30.0)
2      [20.0, 30.0)
3      [20.0, 30.0)
4       [0.0, 10.0)
5      [20.0, 30.0)
6      [20.0, 30.0)
7      [30.0, 50.0)
8      [30.0, 50.0)
9     [50.0, 100.0)
10     [30.0, 50.0)
11     [30.0, 50.0)
12      [0.0, 10.0)
13     [10.0, 20.0)
14    [50.0, 100.0)
15              NaN
Name: age, dtype: category
Categories (5, interval[int64]): [[0, 10) < [10, 20) < [20, 30) < [30, 50) < [50, 100)]

In [10]:
# 預設不包含左邊的界值，包含右邊的界值
# 設定right參數為False，即變為包含左邊的界值，不包含右邊的界值
pd.cut(ages["age"], bins) 

0      (10, 20]
1      (20, 30]
2      (20, 30]
3      (20, 30]
4       (0, 10]
5      (20, 30]
6      (20, 30]
7      (30, 50]
8      (20, 30]
9     (50, 100]
10     (30, 50]
11     (30, 50]
12      (0, 10]
13     (10, 20]
14    (50, 100]
15    (50, 100]
Name: age, dtype: category
Categories (5, interval[int64]): [(0, 10] < (10, 20] < (20, 30] < (30, 50] < (50, 100]]

In [11]:
# precision預設保留三位小數
# precision精度設為2，保留二位小數
pd.cut(ages["age"], 4, precision=2).value_counts() 

(6.91, 30.25]     10
(30.25, 53.5]      3
(76.75, 100.0]     2
(53.5, 76.75]      1
Name: age, dtype: int64

In [12]:
#12-29, 30-49, 50-65
#[18,22,25,27,7,21,23,37,30,61,45,41,9,18,80,100]
bins = [-np.inf,12,30,50,66,np.inf]
pd.cut(ages["age"], bins, retbins = True, labels = ["小於12歲不列入評估","網購低消費族","網購高消費族","網購中消費族","大於65歲不列入評估"],right = False)

(0         網購低消費族
 1         網購低消費族
 2         網購低消費族
 3         網購低消費族
 4     小於12歲不列入評估
 5         網購低消費族
 6         網購低消費族
 7         網購高消費族
 8         網購高消費族
 9         網購中消費族
 10        網購高消費族
 11        網購高消費族
 12    小於12歲不列入評估
 13        網購低消費族
 14    大於65歲不列入評估
 15    大於65歲不列入評估
 Name: age, dtype: category
 Categories (5, object): ['小於12歲不列入評估' < '網購低消費族' < '網購高消費族' < '網購中消費族' < '大於65歲不列入評估'],
 array([-inf,  12.,  30.,  50.,  66.,  inf]))

In [13]:
pd.cut(ages["age"], bins, retbins = True, labels = ["小於12歲不列入評估","網購低消費族","網購高消費族","網購中消費族","大於65歲不列入評估"],right = False)

(0         網購低消費族
 1         網購低消費族
 2         網購低消費族
 3         網購低消費族
 4     小於12歲不列入評估
 5         網購低消費族
 6         網購低消費族
 7         網購高消費族
 8         網購高消費族
 9         網購中消費族
 10        網購高消費族
 11        網購高消費族
 12    小於12歲不列入評估
 13        網購低消費族
 14    大於65歲不列入評估
 15    大於65歲不列入評估
 Name: age, dtype: category
 Categories (5, object): ['小於12歲不列入評估' < '網購低消費族' < '網購高消費族' < '網購中消費族' < '大於65歲不列入評估'],
 array([-inf,  12.,  30.,  50.,  66.,  inf]))