## [作業重點]
使用 Sklearn 中的 Lasso, Ridge 模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義。

機器學習的模型非常多種，但要訓練的資料多半有固定的格式，確保你了解訓練資料的格式為何，這樣在應用新模型時，就能夠最快的上手開始訓練！

## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則化來觀察訓練情形。

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
import warnings
warnings.filterwarnings('ignore')

### 波斯頓房價資料集

In [2]:
# 讀取波斯頓房價資料集
boston = datasets.load_boston()

# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.2, random_state=4)

# 建立一個線性回歸模型
regr = linear_model.LinearRegression()

# 將訓練資料丟進去模型訓練
regr.fit(x_train, y_train)

# 將測試資料丟進去模型得到預測結果
y_pred = regr.predict(x_test)

In [3]:
# 可以看回歸模型的參數值
print(regr.coef_)

[-1.15966452e-01  4.71249231e-02  8.25980146e-03  3.23404531e+00
 -1.66865890e+01  3.88410651e+00 -1.08974442e-02 -1.54129540e+00
  2.93208309e-01 -1.34059383e-02 -9.06296429e-01  8.80823439e-03
 -4.57723846e-01]


In [4]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 25.42


### 紅酒資料集

In [5]:
# 讀取紅酒資料集
wine = datasets.load_wine()

# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(wine.data,  wine.target, test_size=0.1, random_state=4)

# 建立模型
logreg = linear_model.LogisticRegression()

# 訓練模型
logreg.fit(x_train, y_train)

# 預測測試集
y_pred = logreg.predict(x_test)

In [6]:
# 可以看回歸模型的參數值
print(regr.coef_)

[-1.15966452e-01  4.71249231e-02  8.25980146e-03  3.23404531e+00
 -1.66865890e+01  3.88410651e+00 -1.08974442e-02 -1.54129540e+00
  2.93208309e-01 -1.34059383e-02 -9.06296429e-01  8.80823439e-03
 -4.57723846e-01]


In [7]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 0.11


### LASSO

### 波斯頓房價資料集

In [8]:
# 讀取波斯頓房價資料集
boston = datasets.load_boston()
# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.2, random_state=4)

# 建立一個線性回歸模型
lasso = linear_model.Lasso(alpha=3.0)

# 將訓練資料丟進去模型訓練
lasso.fit(x_train, y_train)

# 將測試資料丟進去模型得到預測結果
y_pred = lasso.predict(x_test)

In [9]:
# 印出各特徵對應的係數，可以隨著懲罰力度alpha的增加越來越多的係數變成了0，Lasso Regression 的確可以做特徵選取
lasso.coef_

array([-0.        ,  0.02919918, -0.        ,  0.        ,  0.        ,
        0.        ,  0.03886994, -0.        ,  0.03135877, -0.00891871,
       -0.2596793 ,  0.00514094, -0.76079107])

In [10]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 37.70


### 紅酒資料集

In [11]:
# 讀取紅酒資料集
wine = datasets.load_wine()

# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(wine.data,  wine.target, test_size=0.2, random_state=4)

# 建立模型
lasso = linear_model.Lasso(alpha=3.0)

# 訓練模型
lasso.fit(x_train, y_train)

# 預測測試集
y_pred = lasso.predict(x_test)

In [12]:
# 印出各特徵對應的係數，可以看到許多係數都變成 0，Lasso Regression 的確可以做特徵選取
lasso.coef_

array([ 0.       ,  0.       ,  0.       ,  0.       ,  0.       ,
       -0.       , -0.       ,  0.       , -0.       ,  0.       ,
       -0.       , -0.       , -0.0015755])

In [13]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 0.42


### Ridge

### 波斯頓房價資料集

In [14]:
# 讀取波斯頓房價資料集
boston = datasets.load_boston()

# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(boston.data, boston.target, test_size=0.2, random_state=4)

# 建立一個線性回歸模型
ridge = linear_model.Ridge(alpha=3.0)

# 將訓練資料丟進去模型訓練
ridge.fit(x_train, y_train)

# 將測試資料丟進去模型得到預測結果
y_pred = ridge.predict(x_test)

In [15]:
# 印出 Ridge 的參數，可以很明顯看到比起 Linear Regression，參數的數值都明顯小了許多
ridge.coef_

array([-0.11064437,  0.04864843, -0.04254266,  2.65985752, -4.95618445,
        3.91491587, -0.02075033, -1.36870789,  0.26655236, -0.01427293,
       -0.78983702,  0.00935803, -0.47552246])

In [16]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 26.04


### 紅酒資料集

In [17]:
# 讀取紅酒資料集
wine = datasets.load_wine()

# 切分訓練集/測試集
x_train, x_test, y_train, y_test = train_test_split(wine.data,  wine.target, test_size=0.2, random_state=4)

# 建立模型
ridge = linear_model.Ridge(alpha=3.0)

# 訓練模型
ridge.fit(x_train, y_train)

# 預測測試集
y_pred = ridge.predict(x_test)

In [18]:
# 印出 Ridge 的參數，可以很明顯看到比起 Linear Regression，參數的數值都明顯小了許多
ridge.coef_

array([-0.1020657 ,  0.01969654, -0.16804995,  0.04301706,  0.00040643,
        0.06407742, -0.29541195, -0.0514518 ,  0.03083828,  0.08081211,
       -0.10350943, -0.25863362, -0.0008003 ])

In [19]:
# 預測值與實際值的差距，使用 MSE
print("Mean squared error: %.2f"
      % mean_squared_error(y_test, y_pred))

Mean squared error: 0.07
